# Generated by Django 3.0.5 on 2020-05-26 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='project/')),
                ('descrition', models.TextField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='Draft', max_length=50)),
                ('type', models.CharField(choices=[('Back-End', 'Back End'), ('Front-End', 'Front End')], default='Back End', max_length=20)),
            ],
            options={
                'ordering': ('-updated', '-publish'),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project')),
                ('multi_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='mypf.Project')),
            ],
        ),
    ]
