# Generated by Django 3.0.5 on 2020-05-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descrition',
            new_name='descrpition',
        ),
    ]
