# Generated by Django 3.0.5 on 2020-05-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypf', '0002_auto_20200527_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descrpition',
            new_name='description',
        ),
    ]
