# Generated by Django 3.0.5 on 2020-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypf', '0003_auto_20200527_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-sent_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
    ]
